In [5]:
import os
import pandas as pd

In [6]:
# Define the directory containing the CSV files
dir_path = r'C:\Users\linxi\OneDrive\Desktop\NYU\Computational Cognitive Modelling\project\分词数据'

# Create a list to store dfs
dfs = []

# Iterate through the files in the directory
for filename in os.listdir(dir_path):
    file_path = os.path.join(dir_path, filename)
    try:
        # Read the CSV file into a df
        df = pd.read_csv(file_path)
        dfs.append(df)  # Add the df to the list
    except Exception as e:
        print(f"Error reading {filename}: {e}")

# Combine all dfs into one 
combined_df = pd.concat(dfs, ignore_index=True)

# Print the combined df (or save it to a file)
print(combined_df)

        Column1  Column2  Column1_Tag  Column2_Tag
0       晚风摇树树还挺  晨露润花花更红      1011111      1011011
1       愿景天成无墨迹  万方乐奏有于阗      1101110      1001111
2       丹枫江冷人初去  绿柳堤新燕复来      1001111      1001011
3       闲来野钓人稀处  兴起高歌酒醉中      1111111      1010101
4       投石向天跟命斗  闭门问卷与时争      1111111      1000111
...         ...      ...          ...          ...
344944  月来抢我杯中酒  风过还君梦里香      1111110      1111111
344945  明月东升莺入谷  夕阳西下燕归巢      1011110      1000111
344946  治世之音安以乐  君子有酒旨且多      1011111      1011111
344947  天高风谱风云曲  地远心追心梦诗      1111100      1111101
344948  避荤吃素沙门在  大意粗心菩萨蛮      1111101      1010101

[344949 rows x 4 columns]

In [9]:
# These matched data are used to train the word segmentation model
matched_data = combined_df[combined_df['Column1_Tag']==combined_df['Column2_Tag']]
matched_data.to_csv('matched_data.csv')
matched_data

        Column1  Column2  Column1_Tag  Column2_Tag
7       常夸海口无人信  不做夜郎有客邀      1110111      1110111
12      放倒昆仑当睡枕  拿来北斗做汤勺      1110110      1110110
14      醉酒非因人寂寞  凭栏只为意阑珊      1111110      1111110
22      西子湖边逢暮雨  东坡路上戏朝云      1001111      1001111
27      收了相思肥了梦  舞回寂寞湿回云      1110111      1110111
...         ...      ...          ...          ...
344937  千山遥望云牵手  七女相逢雾搭桥      1110111      1110111
344938  畏民喦其难其慎  敕天命惟几惟康      1111111      1111111
344939  文章道德参天地  礼乐诗书贯古今      1010110      1010110
344943  怜花不惜三千墨  好酒何珍十万金      1110101      1110101
344946  治世之音安以乐  君子有酒旨且多      1011111      1011111

[67325 rows x 4 columns]

In [8]:
unmatched_data = combined_df[combined_df['Column1_Tag']!=combined_df['Column2_Tag']]
unmatched_data.to_csv('unmatched_data.csv')
unmatched_data

        Column1  Column2  Column1_Tag  Column2_Tag
0       晚风摇树树还挺  晨露润花花更红      1011111      1011011
1       愿景天成无墨迹  万方乐奏有于阗      1101110      1001111
2       丹枫江冷人初去  绿柳堤新燕复来      1001111      1001011
3       闲来野钓人稀处  兴起高歌酒醉中      1111111      1010101
4       投石向天跟命斗  闭门问卷与时争      1111111      1000111
...         ...      ...          ...          ...
344942  近来疏懒人间事  只爱清芬墨里香      1010101      1110100
344944  月来抢我杯中酒  风过还君梦里香      1111110      1111111
344945  明月东升莺入谷  夕阳西下燕归巢      1011110      1000111
344947  天高风谱风云曲  地远心追心梦诗      1111100      1111101
344948  避荤吃素沙门在  大意粗心菩萨蛮      1111101      1010101

[277624 rows x 4 columns]